name: Telegram News

on:
  schedule:
    - cron: "0 10,18 * * *"   # 10:00 UTC = 12:00 und 20:00 Europe/Prague
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install requests feedparser pytz
      - name: Run news.py
        run: python news.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
